name: Update IPTV playlist
permissions:
  contents: write

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install playwright
          python -m playwright install --with-deps

      - name: Run updater
        run: |
          python scripts/update_playlist.py --use-playwright

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add data/iptv.m3u8 scripts/last_good.json || true
            git commit -m "Auto-update playlist: $(date -u +'%Y-%m-%d %H:%M UTC')" || true
            git push
          else
            echo "No changes"
          fi