name: Update IPTV playlist
permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'    # run hourly at minute 0 (UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install playwright
          python -m playwright install --with-deps

      - name: Run updater
        env:
          CHECK_THRESHOLD_MINUTES: "30"
        run: |
          python scripts/update_playlist.py --use-playwright

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # stage and commit any changes
          if git diff --quiet -- data/iptv.m3u8 scripts/last_good.json; then
            echo "No changes"
            exit 0
          fi
          git add data/iptv.m3u8 scripts/last_good.json || true
          git commit -m "Auto-update playlist: $(date -u +'%Y-%m-%d %H:%M UTC')" || true

          # fetch remote and rebase our local commit(s) on top of the latest main
          git fetch origin main
          if ! git rebase origin/main; then
            echo "Rebase failed; attempting rebase with autostash"
            if ! git rebase --autostash origin/main; then
              echo "Rebase ultimately failed; aborting push to avoid conflicts"
              git rebase --abort || true
              exit 0
            fi
          fi
          git push origin HEAD